shamefullyHoist: true

catalog:
  "@clack/prompts": ^0.11.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.3
  eslint: ^9.36.0
  tsdown: ^0.15.6

onlyBuiltDependencies:
  - esbuild
