shamefullyHoist: true

catalog:
  "@antfu/eslint-config": ^4.13.1
  "@clack/prompts": ^0.10.1
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.1
  eslint: ^9.26.0
  tsdown: ^0.11.9

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver
