shamefullyHoist: true

packages:
  - packages/*

catalog:
  "@nuxt/devtools": ^2.6.5
  "@nuxt/icon": ^2.0.0
  "@pinia/nuxt": ^0.11.2
  "@unocss/nuxt": ^66.5.2
  "@vueuse/core": ^13.9.0
  "@vueuse/nuxt": ^13.9.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/stylelint-config": ^0.3.3
  eslint: ^9.36.0
  nuxt: ^4.1.2
  pinia: ^3.0.3
  unocss: ^66.5.2
  vue: ^3.5.22
  vue-router: ^4.5.1
  vue-tsc: ^3.1.0
