shamefullyHoist: true

packages:
  - packages/*

catalog:
  "@nuxt/devtools": ^2.6.2
  "@nuxt/icon": ^1.15.0
  "@pinia/nuxt": ^0.11.2
  "@unocss/nuxt": ^66.4.2
  "@vueuse/core": ^13.6.0
  "@vueuse/nuxt": ^13.6.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/stylelint-config": ^0.3.3
  eslint: ^9.33.0
  nuxt: ^4.0.3
  pinia: ^3.0.3
  unocss: ^66.4.2
  vue: ^3.5.18
  vue-router: ^4.5.1
  vue-tsc: ^3.0.5
