packages:
  - packages/*

catalog:
  "@antfu/eslint-config": ^4.12.0
  "@zinkawaii/eslint-config": ^0.2.2
  "@zinkawaii/tsconfig": ^0.0.1
  bumpp: ^10.1.0
  eslint: ^9.24.0
  tsdown: ^0.8.0
  vitest: ^3.1.1