packages:
  - packages/*

catalog:
  "@antfu/eslint-config": ^4.12.0
  "@zinkawaii/eslint-config": ^0.2.3
  "@zinkawaii/tsconfig": ^0.0.1
  bumpp: ^10.1.0
  eslint: ^9.25.1
  tsdown: ^0.10.0
  vitest: ^3.1.2